version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: project-wjc-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: project-wjc
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-wjc-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/project-wjc?authSource=admin
      - JWT_SECRET=dev-jwt-secret-key
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      # Add your DatoCMS credentials here
      - DATOCMS_READONLY_TOKEN=${DATOCMS_READONLY_TOKEN}
      - DATOCMS_BASE_URL=https://graphql.datocms.com
      # Email configuration (optional for development)
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      # Rate limiting
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      # For development - mount source code
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  # MongoDB Express (Optional - for database management)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: project-wjc-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - app-network
    profiles:
      - mongo-ui

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local